spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${URL-DB:localhost}:${PORT-DB:5432}/${DB-NAME:ms-dict}?reWriteBatchedInserts=true
    username: ${POSTGRES-USER:postgres}
    password: ${POSTGRES-PASSWORD:postgres}
    auto-commit: false
    maximumPoolSize: 10
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10

generator:
  root: /Projects/java/centurion/afl_default/ms-dict-development/server/src/main/java
  tables:
    include: country, town, airport, currency, country_currency #country_zone_airport
  entities:
    enable: true
    packages: ru.aeroflot.dict.v1.entity
    template: src/main/resources/templates/entity.xsl
    suffix: V1Entity
  repository:
    enable: true
    packages: ru.aeroflot.dict.v1.repository
    template: src/main/resources/templates/repository.xsl
    suffix: V1Repository
    save-part-start: \/\*\* User chages
  model:
    enable: true
    generate-data: true
    packages: ru.aeroflot.dict.v1.model
    template: src/main/resources/templates/model.xsl
    suffix: V1Dto
    suffix-data: V1Data
  mapper:
    enable: true
    packages: ru.aeroflot.dict.v1.mapper
    template: src/main/resources/templates/mapper.xsl
    suffix: V1Mapper
  service:
    enable: true
    packages: ru.aeroflot.dict.v1.service
    template: src/main/resources/templates/service.xsl
    suffix: V1Service
  controller:
    enable: true
    packages: ru.aeroflot.dict.v1.controller
    template: src/main/resources/templates/controller.xsl
    suffix: V1Controller


