spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:ed-go}?reWriteBatchedInserts=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    auto-commit: false
    maximumPoolSize: 10
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      max-lifetime: 360000
      connection-timeout: 360000
      validation-timeout: 360000

logging:
  level:
    org.c3s.generator: DEBUG


generator:
  root: /Projects/java/ed-spring/ms-dict-static/server/src/main/java
  export: /structure.xml
  catalog: ed-go
  tables:
    include: #systems, stations
    exclude: #system_faction_pending_states, system_faction_recovery_states
  steps:
    entity:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.entity
      template: src/main/resources/templates/entity.xsl
      suffix: Entity
      file-name: ${entity_class_name}.java
    repository:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.repository
      template: src/main/resources/templates/repository.xsl
      suffix: Repository
      save-part-start: \/\*\* User changes
    model:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.model
      template: src/main/resources/templates/model.xsl
      suffix: Dto
    mapper:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.mapper
      template: src/main/resources/templates/mapper.xsl
      suffix: Mapper
    service:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.service
      template: src/main/resources/templates/service.xsl
      suffix: Service
    meta:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.meta
      template: src/main/resources/templates/meta.xsl
      suffix: Meta
    controller:
      enable: true
      packages: org.c3s.edgo.msdict.server.crud.controller
      template: src/main/resources/templates/controller.xsl
      suffix: Controller
    api:
      enable: true
      packages: org.c3s.edgo.msdict.api
      template: src/main/resources/templates/model.xsl
      suffix:
      root: /Projects/java/ed-spring/ms-dict-static/api/src/main/java
    client:
      enable: true
      packages: org.c3s.edgo.msdict.client
      template: src/main/resources/templates/client.vm
      suffix:
      class-name: MsDictClient
      root: /Projects/java/ed-spring/ms-dict-static/client/src/main/java


